# Intro to Numpy 

This notebook is an introduction to the numpy library. Numpy is a powerful library for numerical computing in Python. We will cover the following topics in this notebook:

1. Creating numpy arrays
2. Multi-dimensional arrays
3. Operations on numpy arrays
4. Broadcasting

by Jason Barbour

But first, let's import the numpy library.

In [1]:
import numpy as np

## Creating Numpy Arrays

Numpy arrays are the main data structure in numpy. They are similar to Python lists, but with some key differences. Numpy arrays are homogeneous, meaning that all elements in the array must be of the same data type.

Again, this looks like a downgrade from Python lists, but it is actually a huge advantage. Homogeneous arrays are much faster and more memory efficient than Python lists. 

There are many ways to create numpy arrays. Here are a few examples:

### From a Python List

You can create a numpy array from a Python list using the `np.array()` function.

In [2]:
L = [1, 2, 3, 4, 5, 6, 7, 8, 9]
A = np.array(L)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays of Zeros and Ones

You can create arrays of zeros and ones using the `np.zeros()` and `np.ones()` functions. This can come in handy when you need to initialize an array with a specific shape.

In [3]:
A = np.zeros(10) # zeros(shape)
B = np.ones(10) # ones(shape)
print(A)
print(B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Creating Arrays of specific values

In [4]:
A = np.full(10, 5) # full(shape, value)
A

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

You can also fill an already created array with a specific value.

In [5]:
A.fill(9)
A

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

### Ranges of Values

You can create ranges of values in 2 different ways.

1. `np.arange()`: This is kind of like the `range()` function in Python, but much more powerful. 

In [6]:
np.arange(10) # arange(stop)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10) # arange(start, stop)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Unlike range, you can have non-integer steps in arange.

In [8]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

2. `np.linspace()`: This function creates an array of evenly spaced values between two endpoints. 

In [9]:
np.linspace(0, 10, 21) # linspace(start, stop, num)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

But carefull, make sure you use the right number of points or it may not be what you expect.

In [10]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

If you care about the spacing between the values, use `np.arange()`. If you care about the number of values, use `np.linspace()`.

## Multi-dimensional Arrays

All of the examples above create 1-dimensional arrays. But numpy arrays can have any number of dimensions. All of the above that have a `shape` parameter can be used to create multi-dimensional arrays.

In [11]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

What if you have a 1-dimensional array and you want to convert it to a 2-dimensional array? You can use the `np.reshape()` function to do this.

In [14]:
A = np.arange(9)
A.reshape(3, 3) 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

or equivalently

In [15]:
np.reshape(A, (3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Note that you don't have to specify the size of one of the dimensions. If you pass `-1` as the size of one of the dimensions, numpy will automatically calculate the size of that dimension. For that to work, the size of the other dimension must be a factor of the total number of elements in the array and only use `-1` once.

In [16]:
A = np.arange(9).reshape(3, -1) # -1 means "whatever is needed"
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Operations on Numpy Arrays

### Arithmetic Operations
All the basic arithmetic operations can be done on numpy arrays shown in the table below:

| Operator | Description |
| :---: | :---: |
| + | Addition |
| - | Subtraction |
| / | Division |
| * | Multiplication |
| % | Modulus |
| ** | Exponentiation |

All these operations are done element wise.

In [18]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

In [19]:
a + b

array([11, 22, 33, 44, 55])

In [20]:
a - b

array([ -9, -18, -27, -36, -45])

In [21]:
a * b 

array([ 10,  40,  90, 160, 250])

It works woth all operations in the table above

This will work with scalars as well.

In [22]:
a + 5

array([ 6,  7,  8,  9, 10])

And the `=` variations of these operators work as well.

In [23]:
a += 5  

### Comparison Operators

| Operator | Description |
| :---: | :---: |
| == | Equal |
| != | Not Equal |
| > | Greater Than |
| < | Less Than |
| >= | Greater Than or Equal |
| <= | Less Than or Equal |

These operators also work element wise.

In [24]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 30, 40, 50])
a == b

array([ True,  True, False, False, False])

### Logical Operators

| Operator | Description |
| :---: | :---: |
| & | And |
| \| | Or |
| ~ | Not |
| ^ | Xor |

Agaib, these operators work element wise.

In [25]:
A = np.array([True, False, True, False])
B = np.array([True, True, False, False])
A & B

array([ True, False, False, False])

In addition numpy has some handy function for these operations. For example, `np.all()` and `np.any()`.

`np.all()` checks if all elements in an array are true.

`np.any()` checks if any elements in an array are true.

In [26]:
np.all(A == B)

False

In [27]:
np.any(A == B)

True

### Broadcasting

Broadcasting is a powerful feature of numpy that allows you to perform operations on arrays of different shapes. All you need to know is that the dimensions of the arrays must be compatible. 

How do you know if the dimensions are compatible?

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

1. they are equal, or
2. one of them is 1

If these conditions are not met, a `ValueError` is thrown.

if the arrays have different number of dimensions, the smaller array is padded with ones on its left side.

The simplest example is adding a scalar to an array. 

In [28]:
A = np.array([1, 2, 3, 4, 5])
A + 2 

array([3, 4, 5, 6, 7])

This should not be technically possible, but numpy makes it work by broadcasting the scalar to the shape of the array. Let's look at it step by step.

shape of A is 5
shape of 2 is 1 

The dimensions are compatible, since 1 is compatible with any number. 2 is broadcasted to the shape of A (That is it is copied 5 times).

A + 2 => [1, 2, 3, 4, 5] + [2, 2, 2, 2, 2] = [3, 4, 5, 6, 7]

Let's look at a more complex example.

Take the following two arrays:

In [32]:
A = np.arange(15).reshape(5, 3)
B = np.arange(3)
print(f"A = \n{A}")
print(f"B = {B}")

A = 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
B = [0 1 2]


Take a look at the shapes

In [33]:
print(f"A.shape = {A.shape}")
print(f"B.shape = {B.shape}")

A.shape = (5, 3)
B.shape = (3,)


First, they are not the same number of dimentions, so we need to pad the smaller array with ones on the left side.
```python
A = [[0, 1, 2],
     [3, 4, 5]]
```
A.shape = (2, 3)
```python
B = [[0, 1, 2]]
```
B.shape = (1, 3)

Now they are compatible. because 1 is compatible with any number. And the second dimension is the same.

Numpy will take B and double it along the first dimension to make it the same shape as A.
```python
B = [[0, 1, 2],
     [0, 1, 2]]
```
Now the shapes are the same and the operation can be done element wise.

We expect the result to be:
```python
[[0, 2, 4],
 [3, 5, 7]]
```

In [34]:
A + B

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16]])

This works with any number of dimensions. And with all element wise operations.

Another example:

In [35]:
A = np.arange(12).reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
B = np.arange(4)
B

array([0, 1, 2, 3])

If I want to add B to all columns of A.

Will this work? if not how can we make it work?

In [39]:
C = np.reshape(B,(4, 1)) 
A + C

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

Turning a 1-D array into a column is something you might need to do often. It's called adding a new axis. There is a shorthand for it.

In [40]:
C = B[:,None] # or  [:,np.newaxis] np.newaxis is an alias for None
C 

array([[0],
       [1],
       [2],
       [3]])