# Intro to numpy II

In this notebook we will continue our introduction to numpy. We will cover the following topics:

1. Indexing and Slicing
2. Types in Arrays
3. The Random Module
4. Linear Algebra with Numpy
5. I/O with Numpy

by Jason Barbour


In [1]:
import numpy as np

## Indexing and Slicing

For 1-dimensional arrays, indexing and slicing works the same as Python lists.

In [2]:
array = np.array([1, 2, 3, 4, 5])

In [3]:
array[1:-1]

array([2, 3, 4])

For multi-dimensional arrays, it is a little different.

In [4]:
array = np.arange(100).reshape(10, 10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
array[1:10][0] # This is just the same as the list slicing

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Although you can use the same syntax as Python lists, you can use a more powerful syntax. All you have to do is separate the indices by commas.

```
array[row_index, column_index]
```

In [6]:
array[1,0]

10

It works exactly as expected with slicing!

```
array[start_row:end_row, start_column:end_column]
```

In [7]:
array[1:4, 0:3] # array with rows 1->4 and columns 0->3

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

Let's look at some examples to help you understand.

In [8]:
array[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
array[4,5]

45

In [10]:
array[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [11]:
array[:,:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])

In [12]:
array[:2,:2]

array([[ 0,  1],
       [10, 11]])

In [13]:
array[4,5]

45

In [14]:
array[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [15]:
array[:,:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])

In [16]:
array[:2,:2]

array([[ 0,  1],
       [10, 11]])

In [17]:
array[:,::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [18]:
array[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In addition to indexing with number and slices, you can also index with lists of integers.

```
array[[row1, row2, row3, ...], [column1, column2, column3, ...]]
```

In [19]:
array[[0, 3, 4, 6, 8], :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [20]:
array[:, [0, 3, 4, 6, 8]]

array([[ 0,  3,  4,  6,  8],
       [10, 13, 14, 16, 18],
       [20, 23, 24, 26, 28],
       [30, 33, 34, 36, 38],
       [40, 43, 44, 46, 48],
       [50, 53, 54, 56, 58],
       [60, 63, 64, 66, 68],
       [70, 73, 74, 76, 78],
       [80, 83, 84, 86, 88],
       [90, 93, 94, 96, 98]])

In [21]:
array[[0,3,1,9], [0,3,4,5]]

array([ 0, 33, 14, 95])

There are also other helpfull function to index arrays. For example if you want to get the diagonal:

In [22]:
np.diag(array)

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

### Boolean Indexing

In [23]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [24]:
filters = np.array([[1, 0], 
                    [0, 1]])
filters = np.array([[True, False], 
                    [False, True]]) # same as above

In [25]:
A[filters]

array([0, 1, 3])

In [26]:
A = np.arange(81).reshape(9, 9)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

May seem useless for big inputs untill you remember the boolean operators we talked about earlier.

In [27]:
A % 3 == 0

array([[ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False, False]])

In [28]:
A[A % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78])

In [29]:
(A % 2 == 0) & (A % 3 == 0)

array([[ True, False, False, False, False, False,  True, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [ True, False, False, False, False, False,  True, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [ True, False, False, False, False, False,  True, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [ True, False, False, False, False, False,  True, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [ True, False, False, False, False, False,  True, False, False]])

In [30]:
A[(A % 2 == 0) & (A % 3 == 0)]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78])

## Types in Numpy

In vanilla Python, types are not very important because Python is dynamically typed. But in numpy, types are very important. Most of the time, numpy will automatically determine the type of the array or even convert it to a different type if needed. But sometimes you need to specify the type yourself.

By default, numpy usually uses np.float64 as the default type unless you specify otherwise. There are some exceptions to this, but this is the most common case. Read the documentation to be sure.

In [32]:
B = np.zeros(10, dtype = np.complex128)
B[1] = 5 + 3j
B

array([0.+0.j, 5.+3.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

Another way you might find errors is trying to index with a numpy array.

In [34]:
#A[np.zeros(2)] # This will raise an error

In [35]:
A[np.zeros(2, dtype=np.int64)]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]])

To change the type of an array, you can use `astype()` function. 

In [38]:
C = np.arange(0,5)
C.dtype

dtype('int64')

In [39]:
C = C.astype(np.float64)
C.dtype

dtype('float64')

## The Random Module

In normal Python, you can use the `random` module to generate random numbers. 

In [42]:
import random as rnd
rnd.randint(0, 10)

10

Numpy has its own random module, which is much more powerful. It has many more functions and is much faster than the Python random module. More importantly, it can generate arrays of random numbers.

Let's take a look at some of the most usefull functions that can generate an array of `size` random numbers:

In [48]:
size = 5 # size can be a dimension (a tuple)

To sample numbers from a uniform distribution, you can use:

In [49]:
print(np.random.rand(size)) # uniform in [0, 1]
print(np.random.uniform(-10, 10, size)) # uniform in [-10, 10]

[0.83839504 0.74429762 0.3208859  0.20520249 0.07742095]
[ 7.63760799  0.71010261 -8.36448817  0.57659514  5.81722241]


To sample numbers from a normal distribution, you can use:

In [52]:
print(np.random.randn(size)) # standard normal
print(np.random.normal(5, 4, size)) # N(5, 4)

[ 0.52437019  1.08374506  0.33218358 -0.60811744 -0.33761699]
[ 6.60478562  7.81793569 -0.22678445 12.27829283  9.2878962 ]


To sample integers from a uniform distribution, you can use:

In [53]:
print(np.random.randint(0, 10, size)) # uniform in [0, 10)

[8 0 9 9 5]


#### Choice

`np.random.choice()` is a very usefull function that can sample from a list of elements. You can also specify the probability of each element being chosen.

Imagine you have a list of letters

In [54]:
# ignore this for now 
import string
letters = np.array(list(string.ascii_lowercase))
print(letters)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


You want to sample 10 letters from this list. You can use `np.random.choice()` to do this.

In [58]:
np.random.choice(letters, 10)

array(['n', 'u', 'p', 'q', 'n', 'o', 'g', 'm', 'y', 'g'], dtype='<U1')

If you run it a few times, you might notice that some letters are chosen more than once. This is because the function samples with replacement. If you want to sample without replacement, you can use the `replace` parameter.

In [59]:
np.random.choice(letters, 10, replace=False) 

array(['m', 'k', 's', 'v', 'u', 'h', 'e', 'b', 'a', 'y'], dtype='<U1')

You can also give a probability for each number using the `p` parameter.

#### Shuffle

`np.random.shuffle()` is a function that shuffles arrays in place

In [60]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.random.shuffle(A)
A

array([7, 5, 4, 9, 2, 6, 3, 8, 1, 0])

`np.random.permutation()` is a function that returns a new array with the elements shuffled.

In [62]:
A = np.arange(10)
print(np.random.permutation(A))
print(A)

[8 9 0 7 5 6 1 3 4 2]
[0 1 2 3 4 5 6 7 8 9]


#### Sorting

Now that we know how to shuffle arrays, we can sort them.

In [63]:
A = np.random.randint(0, 10, 10)
print(A)

[5 9 4 4 1 4 5 9 4 2]


In [65]:
print(np.sort(A)) # returns a new array
print(A)

[9 9 5 5 4 4 4 4 2 1]
[5 9 4 4 1 4 5 9 4 2]


In [66]:
A.sort() # in-place
print(A)

[1 2 4 4 4 4 5 5 9 9]


You can also get the indices of the sorted array using `np.argsort()`.

In [71]:
A = np.random.randint(0,10,10)
A

array([1, 1, 7, 1, 6, 5, 9, 4, 6, 9])

In [72]:
np.argsort(A)

array([0, 1, 3, 7, 5, 4, 8, 2, 6, 9])

In other words if you do:

In [74]:
A[np.argsort(A)]

array([1, 1, 1, 4, 5, 6, 6, 7, 9, 9])

You get the sorted array.

How is that useful? 

Well some time you want to sort multiple list according to 1 of them. That's where it is usefull

In [78]:
A = np.array(["Paris", "London", "Berlin"])
B = np.array([ 3, 24, 5])

In [79]:
A[np.argsort(B)]

array(['Paris', 'Berlin', 'London'], dtype='<U6')

## Additional functions

There is the regular function `max`, `argmax`, `min`, `argmin`, `sum`, `mean`, `std`, `var` that you can use on numpy arrays.

In [ ]:
A = np.random.randint(0, 10, 10)
A

In [ ]:
np.max(A), np.argmax(A), np.min(A), np.argmin(A), np.sum(A), np.mean(A), np.median(A), np.std(A), np.var(A), np.argmax(A), np.argmin(A)

# Linear Algebra with Numpy

Perhaps the most important use of numpy is in linear algebra. Numpy has a very powerful linear algebra module that can do almost anything you need.

### Matrix Multiplication

In [ ]:
A = np.array([[4, 5],
              [6, 2]])
B = np.array([[1, 2],
              [3, 4]])

Obviously, you can't use `*` for matrix multiplication since it already do element wise multiplication. Instead you can use `np.dot()` or `@` operator.

In [ ]:
print(np.dot(A,B))
print(A @ B)

Another important thing in Linear algebra is taking the transpose of a matrix. 

In [ ]:
A.T
# or 
np.transpose(A)

The Identity matrix is a very important matrix in linear algebra. It is a square matrix with 1s on the diagonal and 0s everywhere else. 

In [ ]:
np.identity(5)

or you can also do:

In [ ]:
np.eye(5)

`np.eye()` is a generalization of the identity matrix. It can create a matrix with 1s on any diagonal and 0s everywhere else. It can also build non-square matrices.

`np.identity()` just calls np.eye() with diagonal k=0.

In [ ]:
print(np.eye(5, k=2), np.eye(5, 7, k=-2), sep="\n\n")

Addional function designed for linear algebra can be found in the `np.linalg` module. Let's take a look at a few examples

#### More multiplications
When you multiply multiple matrices, sometimes the order of opperation can make the computation faster. Numpy has the function `np.linalg.multi_dot()` that will automatically choose the fastest way to multiply the matrices.

In [ ]:
A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))

In [ ]:
%%timeit
A @ B @ C @ D

In [ ]:
%%timeit
np.linalg.multi_dot([A, B, C, D])

In [ ]:
np.allclose(A @ B @ C @ D, np.linalg.multi_dot([A, B, C, D]), rtol=1e-16)

Of course, you have to make sure the dimentions are compatible with each other

#### Inverse and determinant

You can also calculate the inverse of a matrix using `np.linalg.inv()` and the determinant using `np.linalg.det()`.

In [ ]:
A = np.array([[1, 2], [3, 4]])
np.linalg.inv(A)

In [ ]:
np.linalg.det(A)

#### Solving Systems of Equations

If we have a system of equations that can be writen as 
$$
A x = b
$$
where $A$ is a matrix and $b$ and $x$ are vectors. We want to find x. 

We can solve the system like this:
$$
x = A^{-1} b
$$
in numpy:

PS: I assume here that A is invertable

In [ ]:
M = np.random.random((6000,10000))
A = M @ M.T # This will make A invertable 
x_real = np.random.random(6000)
b = A @ x_real

In [ ]:
%%timeit
x = np.linalg.inv(A) @ b 

In [ ]:
x = np.linalg.inv(A) @ b 
np.max(np.abs(x_real - x))

However, you can use `np.linalg.solve()` to solve the system of equations. It is much faster and more accurate since it uses a different algorithms to solve the system.

In [ ]:
%%timeit
x = np.linalg.solve(A, b)

In [ ]:
x = np.linalg.solve(A, b)
np.max(np.abs(x_real - x))

## I/O with Numpy

Numpy has some functions to read and write arrays to files. For human readable files like text files, csv, etc. you can use `np.loadtxt()` and `np.savetxt()`.

In [80]:
A = np.arange(100).reshape(10,10)
np.savetxt("A.csv", A, delimiter=",", fmt="%d")

In [81]:
A = np.loadtxt("A.csv", delimiter=",")
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

If it doesn't need to be human readable, you can use `np.save()` and `np.load()`. These functions are much faster and more efficient than the text functions. It will save the array in a binary compressed format. Numpy has it's own file format `.npy` for 1 array or `.npz` for multiple arrays.

In [82]:
A = np.arange(100).reshape(10,10)
np.save("A.npy", A)
np.load("A.npy")

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

To save multiple arrays to a `.npz` file, you can use `np.savez()`.

In [83]:
B = np.random.random((1000, 1000))
np.savez("AB.npz", A=A, B=B)
data = np.load("AB.npz")
data["A"]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
data["B"]

array([[0.45699773, 0.27772654, 0.09618409, ..., 0.83172974, 0.65300577,
        0.37694213],
       [0.6673051 , 0.63053497, 0.1808946 , ..., 0.09339695, 0.82618238,
        0.47237202],
       [0.29601936, 0.15863222, 0.97484437, ..., 0.55093521, 0.50966651,
        0.41767464],
       ...,
       [0.47385112, 0.61789037, 0.89973101, ..., 0.78824215, 0.81446788,
        0.54788837],
       [0.63674653, 0.81481796, 0.36189874, ..., 0.20381959, 0.10188378,
        0.50643573],
       [0.49285684, 0.47256723, 0.08962975, ..., 0.20078797, 0.45777339,
        0.05423914]])